# on:
#   push:
#     branches:
#       - main
# name: build gatsby
# jobs:
#   build_gatsby:
#     name: build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1

#       - name: yarn install
#         run: yarn install

#       - name: gatsby build
#         env:
#           GH_API_KEY: ${{ secrets.API_KEY }}
#         run: yarn build

#       - name: deploy
#         uses: maxheld83/ghpages@v0.2.1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           GH_PAT: ${{ secrets.API_KEY }}
#           BUILD_DIR: 'public/'

on:
  push:
    branches:
      - main
name: build gatsby
jobs:
  build_gatsby:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - uses: peaceiris/actions-gh-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
